name: Deploy docs

on:
  push:
    branches:
      - master
      - vuepress-github-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: npm docs:build
      run: yarn docs:build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
       with:
        external_repository: samuel-carnell/reactxjs-docs
        github_token: ${{ secrets.REACTXJS_DOCS }}
        publish_dir: ./docs/.vuepress/dist
        publish_branch: master
