name: Verify Pull Request Title and Body

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - develop

jobs:
  verify-title:
    strategy:
      matrix:
        node-version: [12.x]

    name: Verify Title and Body
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install --frozen-lock
      - name: Run commitlint against PR title
        run: |
          yarn commitlint <<< "
          ${{ github.event.pull_request.title }}
          ${{ github.event.pull_request.body }}"
